package com.fossns.model;

import com.fossns.model.base.BaseChatDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatDetail extends BaseChatDetail<ChatDetail> {
	public static final ChatDetail dao = new ChatDetail().dao();
}
