package com.fossns.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGroups<M extends BaseGroups<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}
	
	public java.lang.String getSummary() {
		return getStr("summary");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}
	
	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

	public void setIsPublic(java.lang.Boolean isPublic) {
		set("is_public", isPublic);
	}
	
	public java.lang.Boolean getIsPublic() {
		return get("is_public");
	}

	public void setIsChecking(java.lang.Boolean isChecking) {
		set("is_checking", isChecking);
	}
	
	public java.lang.Boolean getIsChecking() {
		return get("is_checking");
	}

	public void setSummaryNew(java.lang.String summaryNew) {
		set("summary_new", summaryNew);
	}
	
	public java.lang.String getSummaryNew() {
		return getStr("summary_new");
	}

	public void setCreatorId(java.lang.Integer creatorId) {
		set("creator_id", creatorId);
	}
	
	public java.lang.Integer getCreatorId() {
		return getInt("creator_id");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}
	
	public java.lang.String getImage() {
		return getStr("image");
	}

}
