package com.fossns.model;

import com.fossns.model.base.BaseTopicDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TopicDetail extends BaseTopicDetail<TopicDetail> {
	public static final TopicDetail dao = new TopicDetail().dao();
}
