package com.fossns.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("activities", "id", Activities.class);
		arp.addMapping("banners", "id", Banners.class);
		arp.addMapping("chat_detail", "id", ChatDetail.class);
		arp.addMapping("complaints", "id", Complaints.class);
		arp.addMapping("customers", "id", Customers.class);
		arp.addMapping("friend_apply", "id", FriendApply.class);
		arp.addMapping("friend_dynamic", "id", FriendDynamic.class);
		arp.addMapping("friends", "id", Friends.class);
		arp.addMapping("group_customer", "id", GroupCustomer.class);
		arp.addMapping("group_topic", "id", GroupTopic.class);
		arp.addMapping("groups", "id", Groups.class);
		arp.addMapping("reports", "id", Reports.class);
		arp.addMapping("topic_detail", "id", TopicDetail.class);
		arp.addMapping("topics", "id", Topics.class);
		arp.addMapping("users", "id", Users.class);
	}
}

