package com.fossns.model;

import com.fossns.model.base.BaseActivities;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Activities extends BaseActivities<Activities> {
	public static final Activities dao = new Activities().dao();
}
