package com.fossns.model;

import com.fossns.model.base.BaseComplaints;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Complaints extends BaseComplaints<Complaints> {
	public static final Complaints dao = new Complaints().dao();
}
