package com.fossns.model;

import com.fossns.model.base.BaseCustomers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Customers extends BaseCustomers<Customers> {
	public static final Customers dao = new Customers().dao();
}
