package com.fossns.model;

import com.fossns.model.base.BaseFriendApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FriendApply extends BaseFriendApply<FriendApply> {
	public static final FriendApply dao = new FriendApply().dao();
}
