package com.fossns.model;

import com.fossns.model.base.BaseGroupTopic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupTopic extends BaseGroupTopic<GroupTopic> {
	public static final GroupTopic dao = new GroupTopic().dao();
}
