package com.fossns.model;

import com.fossns.model.base.BaseGroupCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupCustomer extends BaseGroupCustomer<GroupCustomer> {
	public static final GroupCustomer dao = new GroupCustomer().dao();
}
