package com.fossns.model;

import com.fossns.model.base.BaseReports;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reports extends BaseReports<Reports> {
	public static final Reports dao = new Reports().dao();
}
