package com.fossns.model;

import com.fossns.model.base.BaseTopics;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Topics extends BaseTopics<Topics> {
	public static final Topics dao = new Topics().dao();
}
