package com.fossns.model;

import com.fossns.model.base.BaseFriendDynamic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FriendDynamic extends BaseFriendDynamic<FriendDynamic> {
	public static final FriendDynamic dao = new FriendDynamic().dao();
}
