package com.fossns.model;

import com.fossns.model.base.BaseBanners;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Banners extends BaseBanners<Banners> {
	public static final Banners dao = new Banners().dao();
}
