package com.fossns.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFriendApply<M extends BaseFriendApply<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSenderId(java.lang.Integer senderId) {
		set("sender_id", senderId);
	}
	
	public java.lang.Integer getSenderId() {
		return getInt("sender_id");
	}

	public void setReceiverId(java.lang.Integer receiverId) {
		set("receiver_id", receiverId);
	}
	
	public java.lang.Integer getReceiverId() {
		return getInt("receiver_id");
	}

	public void setIsChecking(java.lang.Boolean isChecking) {
		set("is_checking", isChecking);
	}
	
	public java.lang.Boolean getIsChecking() {
		return get("is_checking");
	}

}
